In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
mat1=np.array([[1,2,3,4,5],[5,4,3,2,1],[6,7,8,9,0],[0,9,8,7,6]])
res=np.matrix(mat1)
print(res)

In [3]:
np.random.rand(2,2)

array([[0.81775596, 0.71943774],
       [0.81658769, 0.41529705]])

In [ ]:
mat2=np.array([[11,12],[13,14],[15,16]])
print("Original Matrix:\n")
print(mat2)
print("\nTranspose Of The Matix:\n")
print(mat2.T)

mat3=np.array([[11,12],[13,14]])
print(mat3)
print("\n")
detmin=np.linalg.det(mat3)
print("Determinent: \n")
print(mat3)

In [ ]:
rand1=np.matrix(np.random.rand(5,4))
print(rand1)

In [ ]:
mat1=np.array([[2,2],[2,2]])
print("First Matrix:\n")
print(mat1)
mat2=np.array([[3,4],[5,6]])
print("Second Matrix:\n")
print(mat2)
print("\n")
res=np.matrix(mat1)*np.matrix(mat2)
print("Multiplication Of Matrix:\n")
print(res)

In [ ]:
mat4=np.array([[2,2],[2,2]])
print("First Matrix:\n")
print(mat4)
mat5=np.array([[3,4],[5,6]])
print("Second Matrix:\n")
print(mat5)
print("\n")
res2=np.multiply(mat4,mat5)
print("Multiplication Of Matrix:\n")
print(res2)


In [10]:
MatArr=np.array([[2, 1], [2, -2], [3, -3]])
print(MatArr)
print("Mean:\n",np.mean(MatArr))
print("Median:\n",np.median(MatArr))

[[ 2  1]
 [ 2 -2]
 [ 3 -3]]
Mean:
 0.5
Median:
 1.5


In [11]:
Mat2=np.array([[1,2,3,4,5],[5,4,3,2,1],[6,7,8,9,0],[0,9,8,7,6]])
print(Mat2)
print("Each Row in Second Column:",Mat2[0:,1])

[[1 2 3 4 5]
 [5 4 3 2 1]
 [6 7 8 9 0]
 [0 9 8 7 6]]
Each Row in Second Column: [2 4 7 9]


In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv('https://raw.githubusercontent.com/MehtaUrjit/ML/main/iris.csv')
arr1=np.array(data.head(5))
mat5=np.array([arr1[:,0],arr1[:,1],arr1[:,2],arr1[:,3]])
res=mat5-np.mean(mat5,axis=0)
print(res)